name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: test-execution
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal


  deploy:
    name: Dockploy Deploy
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: ping Dockploy webhook
        run: curl -X POST "${{ secrets.DOKPLOY_WEBHOOK }}"
